#!/bin/bash

source ./public.sh

apt-get install -y memcached
service memcached restart

cat >/etc/swift/proxy-server.conf <<EOF
[DEFAULT]
bind_port = 8080
workers = 8
user = root
log_facility = LOG_LOCAL4
[pipeline:main]
# Yes, proxy-logging appears twice. This is so that
# middleware-originated requests get logged too.
pipeline = catch_errors healthcheck proxy-logging cache bulk slo ratelimit tempurl tempauth staticweb account-quotas container-quotas proxy-logging proxy-server

[filter:catch_errors]
use = egg:swift#catch_errors

[filter:healthcheck]
use = egg:swift#healthcheck

[filter:proxy-logging]
use = egg:swift#proxy_logging

[filter:bulk]
use = egg:swift#bulk

[filter:ratelimit]
use = egg:swift#ratelimit

[filter:crossdomain]
use = egg:swift#crossdomain

[filter:slo]
use = egg:swift#slo
min_segment_size = 65536
[filter:tempurl]
use = egg:swift#tempurl

[filter:tempauth]
use = egg:swift#tempauth
user_admin_admin = admin .admin .reseller_admin
user_test_tester = testing .admin
user_test2_tester2 = testing2 .admin
user_test_tester3 = testing3

[filter:staticweb]
use = egg:swift#staticweb

[filter:account-quotas]
use = egg:swift#account_quotas

[filter:container-quotas]
use = egg:swift#container_quotas

[filter:cache]
use = egg:swift#memcache
memcache_servers = 127.0.0.1:11211

[app:proxy-server]
use = egg:swift#proxy
allow_account_management = true
account_autocreate = true
EOF
