#!/bin/bash

DISK=xvdb

find /var/log/swift -type f -exec rm -f {} \;
sudo umount /dev/$DISK
sudo mkfs.xfs -f /dev/$DISK
sudo mount /dev/$DISK /srv/node
sudo rm -f /var/log/debug /var/log/messages /var/log/rsyncd.log /var/log/syslog
find /var/cache/swift* -type f -name *.recon -exec rm -f {} \;
sudo service rsyslog restart
sudo service memcached restart
